# Generated by Django 4.2.3 on 2023-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportdatalogs',
            name='date',
        ),
        migrations.AddField(
            model_name='exportdatalogs',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
